# Generated by Django 3.0.2 on 2020-01-16 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='polls/static/images/user.png', storage=server.models.MediaFileSystemStorage(), upload_to='polls/static/images')),
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
