# Generated by Django 3.0.2 on 2020-01-16 16:16

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Def name', max_length=20)),
                ('text', models.TextField(default='Def text')),
                ('birth_date', models.DateField(blank=True, default='1980-1-1')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('photo', models.ImageField(blank=True, default='polls/static/images/user.png', storage=server.models.MediaFileSystemStorage(), upload_to='polls/static/images')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Doctor')),
            ],
        ),
    ]
