# Generated by Django 3.0.2 on 2020-01-16 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 1, 16, 17, 16, 39, 283201))),
                ('gas_sensors', models.CharField(default='{}', max_length=10000)),
                ('distance', models.CharField(default='{}', max_length=10000)),
                ('temperature', models.CharField(default='{}', max_length=10000)),
                ('camera_kurokesu', models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='polls/static/images/tests')),
                ('camera_rasp', models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='polls/static/images/tests')),
                ('thermal_camera', models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='polls/static/images/tests')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Doctor')),
            ],
        ),
    ]
