# Generated by Django 3.0.2 on 2020-01-30 11:56

import datetime
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200130_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, default='server/static/images/user.png', storage=server.models.MediaFileSystemStorage(), upload_to='server/static/images'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 12, 56, 1, 381190)),
        ),
    ]
