# Generated by Django 3.0.2 on 2020-02-04 12:03

import datetime
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200204_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, default='user.png', storage=server.models.MediaFileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 4, 13, 3, 10, 38115)),
        ),
    ]
