# Generated by Django 2.2.7 on 2020-02-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20200204_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='text',
            field=models.TextField(blank=True, default='Def text'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 11, 59, 23, 991386)),
        ),
    ]
