# Generated by Django 2.2.7 on 2020-02-28 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20200228_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 11, 36, 20, 235323)),
        ),
    ]
