# Generated by Django 2.2.7 on 2020-02-28 11:21

import datetime
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200228_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='camera_kurokesu',
            field=models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='camera_rasp',
            field=models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 12, 21, 47, 705633)),
        ),
        migrations.AlterField(
            model_name='test',
            name='thermal_camera',
            field=models.ImageField(blank=True, storage=server.models.MediaFileSystemStorage(), upload_to='tests/'),
        ),
    ]
