# Generated by Django 2.2.7 on 2020-03-09 09:57

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20200228_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 10, 57, 28, 112161)),
        ),
        migrations.AlterField(
            model_name='test',
            name='distance',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='gas_sensors',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='temperature',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
