# Generated by Django 2.2.7 on 2020-03-09 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20200309_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 11, 13, 3, 313569)),
        ),
        migrations.AlterField(
            model_name='test',
            name='distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
