# Generated by Django 2.2.7 on 2020-04-14 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20200309_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 10, 41, 59, 414529)),
        ),
    ]
