# Generated by Django 2.2.7 on 2020-04-28 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20200414_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='camera_kurokesu',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='camera_rasp',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 13, 16, 20, 22071)),
        ),
        migrations.AlterField(
            model_name='test',
            name='thermal_camera',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
    ]
