# Generated by Django 2.2.7 on 2020-04-28 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20200428_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 18, 37, 53, 926189, tzinfo=utc)),
        ),
    ]
