# Generated by Django 2.2.7 on 2020-04-28 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20200428_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
