# Generated by Django 2.2.7 on 2020-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20200428_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Ruler',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='TissueTypes',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='None', max_length=20),
        ),
    ]
