# Generated by Django 2.2.7 on 2020-10-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20201021_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ImageLeft',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ImageRight',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Imagetherm',
        ),
    ]
