# Generated by Django 2.2.7 on 2020-10-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20201021_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Granulation',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ImageLeft',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ImageRight',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Imagetherm',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Necrosis',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Perimeter',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Slough',
        ),
    ]
