# Generated by Django 2.2.7 on 2020-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_auto_20201021_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='NumberUlcers',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Negative', max_length=10),
        ),
    ]
