# Generated by Django 2.2.7 on 2020-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_test_numberulcers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='NumberUlcers',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=10),
        ),
    ]
