# Generated by Django 2.2.7 on 2020-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_auto_20201022_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Segmented_leftImage',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
    ]
