# Generated by Django 2.2.7 on 2020-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_test_segmented_leftimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Segmented_leftImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
