# Generated by Django 2.2.7 on 2020-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20201026_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Segmented_leftImage_g',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='Segmented_leftImage_n',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='Segmented_leftImage_s',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='TissueTypes',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='None', max_length=50),
        ),
    ]
