# Generated by Django 2.2.7 on 2020-11-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_auto_20201027_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='edited_image',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
    ]
