# Generated by Django 2.2.7 on 2020-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_test_edited_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='edited_image',
            field=models.CharField(max_length=100),
        ),
    ]
