# Generated by Django 2.2.7 on 2020-11-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20201124_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='edited_image',
            new_name='ulcer_edited_image',
        ),
    ]
