# Generated by Django 2.2.7 on 2020-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_auto_20201128_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='distance_ulcer',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='giveDistace_edited_image',
            field=models.ImageField(blank=True, upload_to='edited/'),
        ),
        migrations.AddField(
            model_name='test',
            name='tissueTypes_edited_image',
            field=models.ImageField(blank=True, upload_to='edited/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ulcer_edited_image',
            field=models.ImageField(blank=True, upload_to='edited/'),
        ),
    ]
