# Generated by Django 2.2.7 on 2020-11-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_auto_20201128_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='giveDistace_edited_image',
            new_name='giveDistance_edited_image',
        ),
    ]
