# Generated by Django 2.2.7 on 2020-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0041_auto_20201128_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Pixels_in_UPP',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='Pixels_in_g',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='Pixels_in_n',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='Pixels_in_s',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='0', max_length=20),
        ),
    ]
